# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    ports: 
      - $MONGO_PORT:27017
  backend:
    depends_on:
      - mongo
    image: backend:latest
    environment:
      MONGO_ROOT_USER: $MONGO_ROOT_USER
      MONGO_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_PORT: $MONGO_PORT
      MONGO_HOST: mongo
    ports:
      - 8000:8000
  frontend:
    depends_on:
      - backend
    image: frontend:latest
    ports:
      - 3000:3000